# Generated by Django 4.1.4 on 2022-12-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationwebsite', '0002_remove_product_price_product_stripe_product_id_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
